### ISSUE TITLE
[USERSNAP] Account created with wallet 5FC..Ejoy

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/atlas#2145] opened 2022-02-16 17:20 UTC
**Taken at**: https://play.joystream.org/studio/membership/new
**Fields**:
- Expected Result: Account created with wallet 5FC..Ejoy
- Houston, we have a problem.: Only New Accounts Can be Used for Screened Members

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8ca2e45b-0b4b-426e-9c57-07c3893eee27-annotated_97c3d648-0d72-43cf-af4b-a2449c075c2b.png?etag=f026f7d611384bb5bdb676ec09078f74)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8ca2e45b-0b4b-426e-9c57-07c3893eee27-annotated_97c3d648-0d72-43cf-af4b-a2449c075c2b.png?etag=f026f7d611384bb5bdb676ec09078f74)*

**Browser**: Chrome 96 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 506x905
**Labels**: Bug
**[Open #5 in Usersnap](https://app.usersnap.com/l/feedback/e7a9dce1-7a2f-4af7-b340-9a009f58a0a7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by kdembler** [comment] 2022-06-27 10:38
Duplicate of https://github.com/Joystream/atlas/issues/1840

**Closed as completed by kdembler** 2022-06-27 10:38 UTC
Labels: bug
