### ISSUE TITLE
Should meta info on video tile be positioned consistently?

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#805] opened 2021-06-18 11:14 UTC
Problem: some video titles wrap onto a second line, when this happens in both the videos page and individual channel view, the channel name and some other elements are not aligned anymore. I have highlighted the problem in the below screen capture.

![image](https://user-images.githubusercontent.com/50830161/122552792-d0d7ef80-d047-11eb-84b5-01b9b81755aa.png)

**Comment by kdembler** [comment] 2021-06-18 13:22
I'm not sure if this is a bug. That's how it works on YouTube and I think that's also what our designs assume. Will let the designers decide what to do about that

**Comment by KubaMikolajczyk** [comment] 2021-06-25 09:06
@kdembler is right! This is not a bug - we do allow the title to wrap to the second line and truncate it if it exceeds the second line limit. This will create a difference in height between one line and two line titled videos. It won't be a problem with a sufficient space left below all tiles so the ones with the longer title will still stay in grid and still have a sufficient margin between them and the ones below.

**Comment by kdembler** [comment] 2021-06-25 09:26
Since this is working as desired, I'm gonna close this

**Closed as completed by kdembler** 2021-06-25 09:26 UTC
Labels: question, design, pending-triage, ⚙ component:video tile
