### ISSUE TITLE
Wrong entries in My uploads when channel and video assets upload failed

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#3164] opened 2022-08-23 09:13 UTC
**Steps to reproduce**
1. Make sure your uploads will fail. You can do that by, for example, adding `timeout: 1` option in axios config in `useStartFileUpload.ts`, line 140
2. Create new channel and try to upload an asset (maybe works with channel update too?)
3. Once upload fails, publish a video
4. Video assets upload will fail too, but video assets will be under "Channel assets" tab in My uploads:

<img width="1384" alt="CleanShot 2022-08-23 at 11 11 30@2x" src="https://user-images.githubusercontent.com/12646744/186119986-d1584e15-a5e6-4725-9861-2142138a281c.png">

**Comment by WRadoslaw** [comment] 2023-01-16 13:43
Couldn't reproduce it

<img width="890" alt="image" src="https://user-images.githubusercontent.com/92513933/212692174-cf2f1f83-4c74-47a8-b878-966001b0acda.png">

**Comment by kdembler** [comment] 2023-01-16 13:53
@drillprop I think you've seen this one as well, right?

**Comment by drillprop** [comment] 2023-01-19 07:21
I can't reproduce it as well. Probably was resolved in https://github.com/Joystream/atlas/pull/3383

**Closed as completed by drillprop** 2023-01-19 07:21 UTC
Labels: bug, to-triage
