### ISSUE TITLE
Рroblem with scrolling through the channel list

### ISSUE THREAD

**Issue by andybut** [Joystream/atlas#808] opened 2021-06-19 19:56 UTC
Found a problem with scrolling through the channel list https://play.joystream.org/channels. When the browser window is fully expanded, scrolling is not available.
If you minimize to the window and then expand again, then scrolling starts working normally. Tested on Chrome and Edge for а 
15 '' laptop screen and 29 '' external monitor.
The same applies to https://play.joystream.org/videos, https://play.joystream.org/.

**Comment by kdembler** [comment] 2021-06-20 11:15
Duplicate of #688

**Closed as completed by kdembler** 2021-06-20 11:15 UTC
