### ISSUE TITLE
Improve dialog handling

### ISSUE THREAD

**Issue by kdembler** [Joystream/atlas#559] opened 2021-05-05 10:02 UTC
I think we could use some better dialog management, possibly with its own management hook. It'd be useful to be able to stack dialogs on top of each other (for example, transaction status covering video delete confirmation dialog), maybe we could use some kind of imperative API, as we do with the snackbars. Also #549 could be tackled here. We need to find some good approach for this, let's discuss. Let's create a proposal API first and only then start working on it

**Comment by drillprop** [comment] 2021-05-12 07:06
I started doing some tests already in the playground and I think doing something like we do in the `useSnackbar` is a great idea.

1. First, we could create some context. It will look something like this
```ts
type DialogState = {
  id: string
} & SomeDialogProps

export const DialogProvider: React.FC = ({ children }) => {
	const [dialogs, setDialogs] = useState<DialogState[]>([])
	
	const openDialog = (customId: string, dialogConfig?: SomeDialogProps) => {
           setDialogs([...dialogs, { id: customId, showDialog: true, ...dialogConfig }])
         }

	const closeDialog = (id: string) => {
              // filter dialogs here 
  }

return (
    <DialogContext.Provider value={{ openDialog, closeDialog }}>
      {dialogs.map(({ id, onExitClick, onPrimaryClick ...dialogProps }, idx) => (
        <SomeDialog
          key={idx}
          {...dialogProps}
            onExitClick={(e) => {
            closeDialog(id)
             onExitClick?.(e)
           }}
	   onPrimaryButtonClick={(e) => {
            closeDialog(id)
            onPrimaryButtonClick?.(e)
           }}
					
        />
      ))}
      {children}
    </DialogContext.Provider>
  )
}
```
As you see, it's very similar to the `useSnackbar` context hook. We will keep there an array of dialogs, and just filter or add more of them. Also, as you see I think we should close the dialog every time the user clicks every dialog button(exit button, primary button, or secondary button).  I just think it makes sense to do this as a default behavior. What do you think?

2. Worth mentioning, that we have a minor problem with dialogs. If we have two open dialogs at once and we close one, both of them will disappear: 
 
![dialog bug](https://user-images.githubusercontent.com/51168865/117929894-9f0f9280-b2fd-11eb-8e4d-2507c6dc30c7.gif)

This is caused by `BaseDialog` `useEffect`.To make this work, we will need to move `Portal` here(from `BaseDialog`) and call similar `useEffect` as we call in BaseDialog (but with different condition). Like this:
```ts
useEffect(() => {
    if (!dialogs.length) {
      return
    }
    lockScroll()
    openOverlayContainer()
    return () => {
      unlockScroll()
      closeOverlayContainer()
    }
  }, [dialogs.length, lockScroll, unlockScroll, openOverlayContainer, closeOverlayContainer])


<DialogContext.Provider value={{ openDialog, closeDialog }}>
      <Portal containerRef={overlayContainerRef}>
        {dialogs.map(({ id, onExitClick, ...dialogProps }, idx) => {
         // ...
        })}
      </Portal>
      {children}
  </DialogContext.Provider> 
```
3. Usage of the hook should be pretty much self-explanatory:
```ts
const { openDialog, closeDialog } = useDialogs()

return (
    <Button
      onClick={() =>
        openDialog('playgroundDialog', {
          description: 'This is playground dialog',
          title: 'Cool dialog',
          primaryButtonText: 'Confirm',
          onPrimaryButtonClick: () => {
            // do something here and close dialog
            console.log('some action')
          },
          onExitClick: () => {
            // do something here and close dialog
          },
        })
      }
    >
      Open Dialog
    </Button>
  )
```
`openDialog` will take two parameters - `id` and `dialogOptions`. The first one is mandatory, and we will have to define it in the component. We need it because there is the possibility that we could have several dialogs per view. We also want to have the ability to close it and without `id` it could be hard. With this approach, we could even close the dialog inside `useEffect`, or some other function. We could also add some warning in the console or even throw Error if the `id` is already used. 
The second parameter - `dialogOptions` will be an object very similar to props that we passing to our Dialog.

4. I think we should make MessageDialog or ActionDialog as one. They are very similar and I don't see much sense in keeping them separately.   

5. From this we could go further. I'm not sure yet what to do with `TransactionDialog`. We could add here `openTransactionDialog`, which will take the steps of the transaction as a parameter.  Maybe the dialog will be created separately from the regular dialogs array, because we only use only one Transaction dialog at a time(right?).  
I also thought about adding something like `openDangerDialog` which will take a `variant` parameter that could be `warning` or `error.` These will be the dialogs that will require confirmation or decline.  Pretty much like in the design:
![image](https://user-images.githubusercontent.com/51168865/117930648-8c498d80-b2fe-11eb-9649-7c8d0ed3760d.png)
6. I don't think we should make a lot of changes to `MultiStepper` and `ImageCropDialog`. Let's leave them as they are. I'm a little bit worried that we could encounter the problem which I describe in point 2, and I don't have any solution for this yet.

**Comment by mikkio-j** [comment] 2021-05-12 09:50
I think that the general approach here is a good direction. Have one concern that's present in `useSnackbar` as well and that's calling actions from dialogs/snackbars. For instance:
```
onExitClick={(e) => {
            closeDialog(id)
             onExitClick?.(e)
           }}
	   onPrimaryButtonClick={(e) => {
            closeDialog(id)
            onPrimaryButtonClick?.(e)
           }}
```

We have to make sure that `onExitClick?.(e)` and `onPrimaryButtonClick?.(e)` works properly when we are passing e.g. setState functions. It might not be so obvious but there's a chance that this function will operate on a data that's coming from the moment of calling `openDialog` (so it is not a current state). Some use cases might need to change state so we have too look out for this

**Comment by kdembler** [comment] 2021-05-12 11:10
Some of my thoughts:
1. Maybe the ID could be generated by `openDialog` instead? This way we potentially save some code repetition from each of the consumers. Edit: I see that you use some hardcoded value for the id, like `playgroundDialog`, maybe if we use this then this could stay the way it is. With this approach I suppose we'd define all the IDs on top of the component as hardcoded values? It has nice benefit of not having to store the ID as part of the component state
2. I'm not entirely sure if it's safe to assume that any dialog should be closed when we click one of its buttons. Maybe we add an option that will force the consumer to close the dialog manually? (I think we can close by default)
3. re 2: good catch there, although I'm not sure if we should actually move the `Portal`, if we do then the dialogs we use "manually" (eg. `ImageCropDialog`), will no longer open in the right layer. Maybe we actually don't need a global `overlayContainer`? I think all it does is creating a backdrop for the dialog? What if backdrop was part of the dialog itself instead? Then we could also stack dialogs on top of each other (backdrop of the topmost dialog would also cover the dialogs "underneath").
4. Regarding transaction dialog, I'm not sure we need a hook for that, as I imagine this will be handled by the transaction manager I'm working on now
5. Regarding `openDangerDialog` - do we need a separate function for that? I think this could very well be just an option for regular `openDialog`?

Overall, looks really good! Curious to hear your thoughts on 👆 👆 👆

**Comment by drillprop** [comment] 2021-05-13 06:41
> Some of my thoughts:
> 
> 1. Maybe the ID could be generated by `openDialog` instead? This way we potentially save some code repetition from each of the consumers. Edit: I see that you use some hardcoded value for the id, like `playgroundDialog`, maybe if we use this then this could stay the way it is. With this approach I suppose we'd define all the IDs on top of the component as hardcoded values? It has nice benefit of not having to store the ID as part of the component state

yeah, agree. I also had the idea that we could add make the `id` parameter optional, and if it's not provided openDialog will generate it. The problem is, that I'm not sure how would we close the dialog with generated id. 
So I will start work with hardcoded ids and then will experiment with generated. 

> 2. I'm not entirely sure if it's safe to assume that any dialog should be closed when we click one of its buttons. Maybe we add an option that will force the consumer to close the dialog manually? (I think we can close by default)

We can add the option `shouldCloseOnClick` or something like that and make it `true` by default.

> 3. re 2: good catch there, although I'm not sure if we should actually move the `Portal`, if we do then the dialogs we use "manually" (eg. `ImageCropDialog`), will no longer open in the right layer. Maybe we actually don't need a global `overlayContainer`? I think all it does is creating a backdrop for the dialog? What if backdrop was part of the dialog itself instead? Then we could also stack dialogs on top of each other (backdrop of the topmost dialog would also cover the dialogs "underneath").

I need to investigate it more. I think we could get rid of overlay container and make the backdrop a part of the dialog itself.  

> 4. Regarding transaction dialog, I'm not sure we need a hook for that, as I imagine this will be handled by the transaction manager I'm working on now
> 5. Regarding `openDangerDialog` - do we need a separate function for that? I think this could very well be just an option for regular `openDialog`?

Will just ignore this idea then. 

Last question, what are your thoughts on merging MessageDialog with ActionDialog? Do we actually need them both, or we could make them as one?

**Comment by kdembler** [comment] 2021-05-13 06:50
Regarding Message/Action dialog, I think the Action dialog is currently used only by the image crop. Is there a good reason to merge them though? I'm generally fine with it but we'd need to make sure image crop works properly within message dialog

**Comment by drillprop** [comment] 2021-05-13 10:24
Okay, so I will just leave it as it is for now and not focus on it. Maybe, you're right - there is no need to merge them

**Closed as completed** 2021-06-02 20:08 UTC
Labels: priority:high
