### ISSUE TITLE
CRTs: Add sortable lists in `All Creator Tokens` view

### ISSUE THREAD

**Issue by mochet** [Joystream/atlas#6209] opened 2024-04-23 11:43 UTC
### Description

It would be really good to be able to sort by market cap, revenue, holders etc, currently it is only possible to sort by oldest/newest.
![image](https://github.com/Joystream/atlas/assets/50830161/ea8363b7-10a7-479d-9806-9707d9f48dcc)

### How urgent this is?

Not a blocker, but still worth considering

**Comment by dmtrjsg** [comment] 2024-04-23 12:28
Duplicate of 
- https://github.com/Joystream/atlas/issues/5555

**Closed as completed by dmtrjsg** 2024-04-23 12:28 UTC
Labels: duplicate
