### ISSUE TITLE
Marketplace styling fixes

### ISSUE THREAD

**Issue by attemka** [Joystream/atlas#4203] opened 2023-05-17 13:39 UTC
context taken from https://discord.com/channels/811216481340751934/1035122985905954868/1108386256511053863

@KubaMikolajczyk please update if needed

1. Top padding on marketplace page over the hero slider should be 32px on large breakpoints not 64px and on small 16px look on RWD
https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?type=design&node-id=478-135167&t=hbfp4VS18EDTTlo0-4

2. The gap between hero slides looks like its 16 px? It should be 24px between each item like on designs (24 on large breakpoints 16 on smaller look on RWD) https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?type=design&node-id=478-135167&t=hbfp4VS18EDTTlo0-4

3. Top selling channels section is missing the whole container styling - background + top and pottom paddings - the gap between columns should be 24px on large breakpoints 16px on smaller look on RWD - currently the gap is too small
https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?type=design&node-id=401-19167&t=hbfp4VS18EDTTlo0-4

4. The hero carousel should actually fill 100% of the width of the screen not to be cut to the inner container look at RWD at all hero sliders
https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?type=design&node-id=1%3A15536&t=hbfp4VS18EDTTlo0-1 

5. On small screen breakpoints the ratio of hero sliders player should be different from the rest of larger breakpoints + the placement of icon buttons inside it changes too - check RWD
https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?type=design&node-id=471-105319&t=hbfp4VS18EDTTlo0-4 

6. On smaller breakpoints the size of text below the hero carousel player should be different for both the title and the values of the auction check RWD
https://www.figma.com/file/zQYsZXJo6jmbqcj1kRRmDG/Marketplace?type=design&node-id=471-105319&t=hbfp4VS18EDTTlo0-4

**Comment by dmtrjsg** [comment] 2023-05-18 08:24
duplicate of #4206

**Closed as completed** 2023-05-18 08:24 UTC
Labels: duplicate
