### ISSUE TITLE
Failed loading video state for media player

### ISSUE THREAD

**Issue by bedeho** [Joystream/atlas#74] opened 2020-11-28 13:10 UTC
In particular while developing our storage infrastructure, we should introduce some indication in the UI which shows the user that the video media file could not be fetched. Now it looks like this, which is not great.

![Screen Shot 2020-11-28 at 14 08 54](https://user-images.githubusercontent.com/437292/100516333-7ba7bf80-3183-11eb-8711-d08bc5de4c4d.png)

**Comment by kdembler** [comment] 2020-11-30 07:58
Closing, duplicate of #40

**Closed as completed by kdembler** 2020-11-30 07:58 UTC
Labels: design
