### ISSUE TITLE
Video views count can be increased infinitely by a simple F5 (page refresh)

### ISSUE THREAD

**Issue by singulart** [Joystream/atlas#3047] opened 2022-07-28 21:23 UTC
**Describe the bug**

Simple refreshing of the page increases the view count. 

**To Reproduce**

1. Go to your channel in Atlas that lacks popularity
2. Start refreshing the page
3. Observe view count growing
4. Enjoy the free (but fake) popularity of your channel. 

**Expected behavior**

IMO the algorithm should take into account many things, including, but not limited to, time spent to watch the video, IP address, automated browser behavior etc.

**Screenshots**

**Device (please complete the following information):**

- OS: [e.g. macOS Monterey]
- Browser [e.g. Firefox]

**Additional context**

The problem may actually be deeply rooted in the design choices made by the Atlas team. Using a GraphQL `mutation AddVideoView` a bad faith user can explode the views count without even opening Atlas! Such APIs should never be exposed to end users!

**Comment by singulart** [comment] 2022-07-28 21:37
@kdembler @bedeho WDYT on this?

**Comment by bedeho** [comment] 2022-07-29 07:23
This is true, by design, and anything more robust requires a way to authenticate end users related to apps. So this is just one of those things that DAO needs to solve ;)

**Comment by kdembler** [comment] 2022-08-01 08:51
Yep, please see #539, closing this as a duplicate

**Closed as completed by kdembler** 2022-08-01 08:51 UTC
Labels: bug, pending-triage
